# This is a basic workflow to help you get started with Actions

name: build_and_run_tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request_target:
    types: ["opened", "synchronize"]  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: cmake
        run: |
            ls "$GITHUB_WORKSPACE"
            "$GITHUB_WORKSPACE/test_build.sh"
      - uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
          run: |
            readarray -t changed_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.all }}')"
            changed_file="changed_files[0]"
            echo "${changed_file}"
            task_dir=$(echo $changed_file | grep -o ".*student")
            "$task_dir/build/bin/unit_tests"
            exit $?
            
